apiVersion: v1
kind: Namespace
metadata:
  name: rdm
---
apiVersion: v1
kind: Secret
metadata:
  name: harborcs
  namespace: rdm
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJoZmpjbXdnbC5ncmE1LmNvbnRhaW5lci1yZWdpc3RyeS5vdmgubmV0IjogewoJCQkiYXV0aCI6ICJibXhoWTNKdmRYZzZVR0Z0YVdWeWN6RTRNVFVoIgoJCX0sCgkJImh0dHBzOi8vaW5kZXguZG9ja2VyLmlvL3YxLyI6IHt9LAoJCSJyZWdpc3RyeS50b29scy5zMXBkZ3MuZXUiOiB7fQoJfSwKCSJIdHRwSGVhZGVycyI6IHsKCQkiVXNlci1BZ2VudCI6ICJEb2NrZXItQ2xpZW50LzE5LjAzLjYgKGxpbnV4KSIKCX0KfQ==
type: kubernetes.io/dockerconfigjson