#install postgres chart
helm install rdm-cdb bitnami/postgresql --version 10.9.4 --values values.yaml -n rdm

#upgrade postgres chart
helm upgrade rdm-cdb bitnami/postgresql --version 10.9.4 --values values.yaml -n rdm