image:
  registry: hfjcmwgl.gra5.container-registry.ovh.net
  repository: world-cereal/rdm-postgis
  tag: stable
  pullPolicy: "Always"
  pullSecrets:
    - harborcs

postgresqlUsername: postgres
postgresqlPassword: postgres
postgresqlDatabase: communitydb
postgresqlDataDir: rdm/postgresql/data

volumePermissions:
  enabled: true

shmVolume:
  enabled: true
  chmod:
    enabled: true

persistence: 
  enabled: true 
  mountPath: /rdm/postgresql 
  accessModes:
    - ReadWriteOnce 
  size: 100Gi
 
