ingress:
  enabled: false

env:
  email: ewoc@worldcereal.com

existingSecret: "pgadmin"

nodeSelector:
  system-tag: world-cereal-system

replicas: 1

persistentVolume:
  enabled: false

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app.kubernetes.io/name 
          operator: In
          values:
          - pgadmin4
      topologyKey: kubernetes.io/hostname