nameOverride: rdmpgsql

pgpool:
  # Create pods on System nodes
  nodeSelector: 
    system-tag: world-cereal-system

  podAntiAffinityPreset: hard
  replicaCount: 3
  connectionLifeTime: 120

postgresql:
  existingSecret: rdm-db
  username: postgres
  initdbScripts:
    db.sql: |
      CREATE DATABASE ewocmaster OWNER postgres;
      CREATE DATABASE referencedb OWNER postgres;
      CREATE DATABASE communitydb OWNER postgres;
    postgis.sh: |
      #!/bin/sh
      export PGPASSWORD=$POSTGRES_PASSWORD
      psql ewocmaster -U postgres -c "CREATE EXTENSION postgis";     
      psql referencedb -U postgres -c "CREATE EXTENSION postgis";
      psql communitydb -U postgres -c "CREATE EXTENSION postgis";

  # Create pods on System nodes
  nodeSelector: 
    system-tag: world-cereal-system
  podAntiAffinitypreset: hard
  replicaCount: 3

  # Cause error in data replication when one pod crashes
  livenessProbe:
    enabled: false

  readinessProbe:
    enabled: false

  startupProbe:
    enabled: false

volumePermissions:
  enabled: true

persistence:
  enabled: true
  size: 200Gi # PROD

  extendedConf: |
    max_connections = 512
    shared_buffers = 80MB
