apiVersion: batch/v1
kind: Job
metadata:
  name: rdm-db-migrator
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: rdm-db-migrator-container
          image: hfjcmwgl.gra5.container-registry.ovh.net/world-cereal/rdm/dbmigrator:stable
          imagePullPolicy: IfNotPresent
          env:
            - name: "ConnectionStrings__Default"
              value: "Host=rdm-postgresql;Port=5432;database=ewocmaster;username=postgres;password=postgres;Timeout=120;CommandTimeout=60;"
      restartPolicy: Never
      imagePullSecrets:
        - name: harborcs