#install postgres chart
helm install rdm bitnami/postgresql --version 10.9.4 --values values.yaml -n rdm

#upgrade postgres chart
helm upgrade rdm bitnami/postgresql --version 10.9.4 --values values.yaml -n rdm